swagger: '2.0'

info:
  description: Communication_NotebookのAPI仕様です。
  version: "0.0.0"
  title: Communication_Notebook
paths:
  /kids/:id:
    get:
      tags:
      - "kids"
      summary: "子供の名前、年齢取得"
      description: ""
      parameters:
        -
          name: kid_id
          in: path
          description: 特定の子供の名前と年齢を取得
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: 成功時のレスポンス
          schema:
            title: 子供の年齢と名前を返す
            type: object
            properties:
              name:
                type: string
              age:
                type: integer
        404:
          description: "該当する子供が見つからない"
          schema:
            $ref: '#/definitions/404Error'
  /kid/:id/communication_notebooks:
    get:
      tags:
      - "communication_notebooks"
      summary: "ある子供の全ての連絡帳表示"
      description: ""
      parameters:
        - name: kid_id
          in: path
          description: 子供のID
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: array
            $ref: '#/definitions/Communication_notebook'
        404:
          description: "該当する連絡帳が見つからない"
          schema:
            $ref: '#/definitions/404Error'
  # /kid/:id/communication_notebooks:
    put:
      tags:
      - "communication_notebooks"
      summary: "ある日付の連絡帳を更新"
      description: ""
      parameters:
        - name: "notebook"
          in: body
          description: 連絡帳の特定の情報を更新
          required: true
          schema:
            $ref: '#/definitions/Communication_notebook'
      responses:
        400:
          description: "未入力箇所がある場合無効"
          schema:
            $ref: '#/definitions/400NoInputError'
        200:
          description: "OK"
    post:
      tags:
      - "communication_notebooks"
      summary: "ある日付の連絡帳を登録"
      description: ""
      parameters:
        - name: "notebook"
          in: body
          description: 特定の子供の情報を取得
          required: true
          schema:
            $ref: '#/definitions/Communication_notebook'
      responses:
        400:
          description: "未入力箇所がある場合無効"
          schema:
            $ref: '#/definitions/400NoInputError'
        200:
          description: "OK"
definitions:
  Communication_notebook:
    type: object
    properties:
      id:
        type: string
      daycare_id:
        type: integer
      date:
        type: string
      body_temperature:
        type: integer
      bath:
        type: boolean
      mood:
        type: number
      breakfast:
        type: string
      dinner:
        type: string
      memo:
        type: string
  404Error:
    type: "object"
    properties:
      status:
        type: "integer"
        example: "404"
        format: "int64"
      message:
        type: "string"
        example: "データが見つかりません"
  400NoInputError:
    type: "object"
    properties:
      status:
        type: "integer"
        example: "400"
        format: "int64"
      message:
        type: "string"
        example: "未入力箇所があります"