swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Communication_Notebook

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /kid/{kidId}:
    # This is a HTTP operation
    get:
      tags:
      - "kid"
      # Describe this verb here. Note: you can use markdown
      summary: "子供の名前、年齢取得"
      description: ""
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: kidId
          in: path
          description: 特定の子供の名前と年齢を取得
          required: true
          type: integer
          format: int64
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: 成功時のレスポンス
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: 子供の年齢と名前を返す
            type: object
            properties:
              name:
                type: string
              age:
                type: integer
  /communication_notebook/{kidId}?{date=Date}:
    get:
      tags:
      - "communication_notebook"
      # Describe this verb here. Note: you can use markdown
      summary: "ある日付の連絡帳の詳細表示"
      description: ""
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        - name: kidId
          in: path
          description: 子供のID
          required: true
          type: integer
          format: int32
        - name: date
          in: query
          description: 日付
          required: true
          type: string
          format: date-time
      # Expected responses for this operation:
      responses:
        "200":
          description: "成功時のレスポンス"
          schema:
            $ref: '#/definitions/Communication_notebook'
  /communication_notebook/{kidId}:
    put:
      tags:
      - "communication_notebook"
      # Describe this verb here. Note: you can use markdown
      summary: "ある日付の連絡帳を更新"
      description: ""
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        - name: "notebook"
          in: body
          description: 連絡帳の特定の情報を更新
          required: true
          schema:
            $ref: '#/definitions/Communication_notebook'
      # Expected responses for this operation:
      responses:
        "400":
          description: "未入力箇所がある場合無効"
        "200":
          description: "OK"
  /communication_notebook:
    post:
      tags:
      - "communication_notebook"
      # Describe this verb here. Note: you can use markdown
      summary: "ある日付の連絡帳を登録"
      description: ""
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        - name: "notebook"
          in: body
          description: 特定の子供の情報を取得
          required: true
          schema:
            $ref: '#/definitions/Communication_notebook'
      # Expected responses for this operation:
      responses:
        "400":
          description: "未入力箇所がある場合無効"
        "200":
          description: "OK"
definitions:
  Communication_notebook:
    type: object
    properties:
      id:
        type: string
      daycare_id:
        type: integer
      date:
        type: string
      body_temperature:
        type: integer
      bath:
        type: boolean
      mood:
        type: number
      breakfast:
        type: string
      dinner:
        type: string
      memo:
        type: string